---
data:
  data_location: /home/pedro/datasets/sub37
  extension: "wav"

preprocess:
  sampling_rate: &samplingrate 44100
  block_size: &blocksize 256  # must be a power of 2 if using realtime
  signal_length: &signallength 65536  # 2 ** 16
  n_fft: 2048

  oneshot: false  # crop every audio file to exactly signal length
  out_dir: ./preprocessed/

model:
  hidden_size: 512
  n_harmonic: 100
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize

train:
  scales: [4096, 2048, 1024, 512, 256, 128]
  overlap: .75
